# Author: João Fiuza de Alencastro
# Date: 18/3/2019
#
# This docker-compose file creates a nexus, a sonarqube and a postgresql DB.

version: "3.3"

services:
  sonarqube:    #uid:999
    image: sonarqube
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
     - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
      - /opt/sonarqube/conf:/opt/sonarqube/conf
      - /opt/sonarqube/data:/opt/sonarqube/data
      - /opt/sonarqube/logs:/opt/sonarqube/logs
      - /opt/sonarqube/extensions:/opt/sonarqube/extensions
      - /opt/sonarqube/lib/bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  nexus:
    image: sonatype/nexus3      #uid:200
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "8080:8081"
      - "8082-8083:8082-8083"
    networks:
      - nexusnet
    volumes:
      - /opt/my-nexus-data:/nexus-data


  db:
    image: postgres     #uid: 999
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

  jenkins:
    image: jenkins/jenkins
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - jenkinsnet
    ports:
      - "8085:8080"
      - "50000:50000"
    volumes:
      - /opt/jenkins_home:/var/jenkins_home


networks:
  sonarnet:
  nexusnet:
  jenkinsnet:

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  nexus_data:
  postgresql:
  postgresql_data:
  jenkins_home:
